const currentDate = new Date();

const pegawais = [
  {
    id: 5,
    nama: "Anang Mujiono",
    jabatan: "Tukang",
    nik: "3516182908770001",
    alamat: "Dsn Grogol Gede RT.3 RW.3, Gebangmalang, Mojoanyar, Mojokerto",
    tempatLahir: "Mojokerto",
    tanggalLahir: "1977-08-29",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 6,
    nama: "Juli Hartono",
    jabatan: "Tukang",
    nik: "3517073007800003",
    alamat:
      "Jl Wanara  RT 008 RW 005 Kel. Japanan Kec. Mojowarno, Kab. Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "1980-07-30",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 7,
    nama: "Latip",
    jabatan: "Tukang",
    nik: "3576020111720001",
    alamat:
      "Jl Gunung Anyar RT 003 RW 006 Kel. Gunung Gedangan Kec. Magersari Kota Mojokerto",
    tempatLahir: "Mojokerto",
    tanggalLahir: "1972-11-01",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 8,
    nama: "Moch Arifin",
    jabatan: "Tukang",
    nik: "3576020111860003",
    alamat:
      "Lingk. Gunung Anyar RT.01 RW.06 Kel,Gunung Gedangan  Kec.Magersari Kota Mojokerto  ",
    tempatLahir: "Mojokerto",
    tanggalLahir: "1986-11-01",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 9,
    nama: "Mochamad Barokah",
    jabatan: "Tukang",
    nik: "3517071202830004",
    alamat:
      "Dsn Wonoayu RT.03 RW.01 Kel. Dukuhmojo Kec. Mojoagung, Kab. Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "1984-02-12",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 10,
    nama: "Mochammad Riduwan",
    jabatan: "Tukang",
    nik: "3517062211940001",
    alamat:
      "Dsn Kalibening RT04 RW.02 Kel. Tanggal Rejo Kec. Mojoagung  Kab.Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "1994-11-22",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 11,
    nama: "Noor Kusaeni",
    jabatan: "Tukang",
    nik: "3319060401840008",
    alamat: "Kedungmojo RT 01 , Kel. Tanjungrejo, Kec. Jekulo ",
    tempatLahir: "Kudus",
    tanggalLahir: "1984-01-04",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 12,
    nama: "Rahmat Arifin",
    jabatan: "Tukang",
    nik: "3517072509960002",
    alamat:
      "Dsn Kalibening RT.01 RW.02 Kel. Tanggal Rejo Kec. Mojoagung  Kab.Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: null,
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 13,
    nama: "Sutarno",
    jabatan: "Tukang",
    nik: "3516182808700003",
    alamat: "Pasinan RT.03  RW.02 Kel.Kepuhanyar, Kec. Mojoanyar Kab Mojokerto",
    tempatLahir: "Mojokerto",
    tanggalLahir: "1970-08-28",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 14,
    nama: "Tito Vaka",
    jabatan: "Tukang",
    nik: "3516121705980001",
    alamat: "Kedawung RT.03  RW.02 Kel. Gemekan, Kec. Sooko, Kab. Mojoketo",
    tempatLahir: "Mojokerto",
    tanggalLahir: "1998-05-17",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 15,
    nama: "Tri Martono",
    jabatan: "Tukang",
    nik: "3516181603790001",
    alamat:
      "Grogolgede, RT.01, RW.04 Kel. Gebangmalang, Kec. Mojoanyar, Kab. Mojoagung",
    tempatLahir: "Mojokerto",
    tanggalLahir: "1979-03-16",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 16,
    nama: "Widodo Basuki",
    jabatan: "Tukang",
    nik: "3517060202790007",
    alamat:
      "Dsn Kemodo Utara  RT.03 RW.02, Kel. Dukuhmojo, Kec. Mojoagung, Kab. Mojoagung",
    tempatLahir: "Surabaya",
    tanggalLahir: "1979-02-02",
    profesiId: 3,
    statusPegawaiId: 5,
    gajiPokok: 200000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 17,
    nama: "Anang Ferdiansah",
    jabatan: "Kenek",
    nik: "3516181607950002",
    alamat:
      "Grogol  Gede RT 3 RW 3 Kel. Gebangmalang Kec Mojoanyar Kab Mojokerto",
    tempatLahir: "Mojokerto",
    tanggalLahir: "1998-07-16",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 18,
    nama: "Diki Dwistiawan ",
    jabatan: "Kenek",
    nik: "3517060904010001",
    alamat:
      "Dusun Kedunglumpang, Kel Keudnglumpang Kec. Mojoagung, Kab. Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "2001-04-09",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 19,
    nama: "Dimas Kurniawan ",
    jabatan: "Kenek",
    nik: "3516011906060001",
    alamat: "Jembul RT 3 RW 2 Kecamatan Jatirejo Kab. Mojokerto",
    tempatLahir: "Mojokerto",
    tanggalLahir: "2006-06-19",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 20,
    nama: "Eko Oktariza",
    jabatan: "Kenek",
    nik: "1671022601870006",
    alamat:
      "Jl Teratai Perum Ceria Cipta Utama Griya RT.03 RW.03, Kel. Indralaya Indah. Kec. Indralaya Kab. Ogan Ilir, Sumatera Selatan",
    tempatLahir: "Palembang",
    tanggalLahir: "1987-01-26",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 21,
    nama: "Fahri Amrulloh",
    jabatan: "Kenek",
    nik: "3576022708060001",
    alamat:
      "Gedangan, RT.04, RW.07, Kel. Gununggedangan, Kec Magersari, Kota Mojokerto",
    tempatLahir: "Mojokerto",
    tanggalLahir: "2006-08-27",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 22,
    nama: "Guana Nazar Devansyah",
    jabatan: "Kenek",
    nik: "3517060809040003",
    alamat:
      "Jl Rambutan No 57 RT.05, RW.04, Kel. Kademangan, Kec. Mojoagung, Kab Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "2004-09-08",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 23,
    nama: "Imam Pambudi",
    jabatan: "Kenek",
    nik: "3517062505770003",
    alamat:
      "Dsn Pandean,  RT.06 RW. 02 Kel. Miagan Kec. Mojoagung. Kab, Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "1977-05-25",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 24,
    nama: "Maulana Iskhak",
    jabatan: "Kenek",
    nik: "3517072111050003",
    alamat:
      "Jl. Pahlawan RT.03 RW.03, Kel. Sukomulyo. Kec. Mojowarno. Kab. Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "2005-11-21",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 25,
    nama: "Miftakhul Mashudin",
    jabatan: "Kenek",
    nik: "3516010404050001",
    alamat: "Jembul RT 3 RW 2 Kecamatan Jatirejo Kab. Mojokerto",
    tempatLahir: "Mojokerto",
    tanggalLahir: "2005-04-04",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 26,
    nama: "Moch Nor Alfandi",
    jabatan: "Kenek",
    nik: "3517061303010005",
    alamat:
      "Dsn Pandean,  RT.01 RW. 02 Kel. Miagan Kec. Mojoagung. Kab, Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "2001-03-13",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 27,
    nama: "Muhammad Abdul Wakhid",
    jabatan: "Kenek",
    nik: "3516012912060001",
    alamat: "Jembul RT 4 RW 2 Kecamatan Jatirejo Kab. Mojokerto",
    tempatLahir: "Mojokerto",
    tanggalLahir: "2006-12-29",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 28,
    nama: "Muhammad Khamim",
    jabatan: "Kenek",
    nik: "3517071003930002",
    alamat: "Jl Wanara  RT 12 RW 06 Kel. Japanan, Kec. Mojowarno, Kab. Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "1993-01-10",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 29,
    nama: "Redo Wahyudianto",
    jabatan: "Kenek",
    nik: "3517602510010001",
    alamat:
      "Dsn Kalibening  RT 05 RW 02, Kel. Tanggalrejo. Kec. Mojoagung, Kab. Jombang",
    tempatLahir: "Mojokerto",
    tanggalLahir: "2001-10-28",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 30,
    nama: "Rifki Ardian",
    jabatan: "Kenek",
    nik: "351706090760001",
    alamat:
      "Kedunglumpang RT 03 RW 01 Kel. Kedunglumpang Kec. Mojoagung Kab.Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "2006-07-09",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 31,
    nama: "Roby Syahputra",
    jabatan: "Kenek",
    nik: "3516130111000004",
    alamat: "Blimbing RT 14 RW 04 Kel Blimbingsari Kec. Sooko  Kab.Mojokerto ",
    tempatLahir: "Mojokerto",
    tanggalLahir: "2000-11-01",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 32,
    nama: "Sahrul Romadhoni Diky Saputra",
    jabatan: "Kenek",
    nik: "3516012009060002",
    alamat: "Jembul RT 4 RW 2 Kecamatan Jatirejo Kab. Mojokerto",
    tempatLahir: "Mojokerto",
    tanggalLahir: "2006-09-20",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 33,
    nama: "Wahyu Aprilianto",
    jabatan: "Kenek",
    nik: "3576020504020004",
    alamat:
      "Grogol  Gede RT 3 RW 3 Kel. Gebangmalang Kec Mojoanyar  Kab Mojokerto",
    tempatLahir: "Kediri",
    tanggalLahir: "2002-04-05",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
  {
    id: 34,
    nama: "Yulio Candra Kristianto",
    jabatan: "Kenek",
    nik: "3517212110070001",
    alamat:
      "Dsn Bogorame  RT 16 RW 08 Kel. Kedungbogo Kec. Ngusikan Kab. Jombang",
    tempatLahir: "Jombang",
    tanggalLahir: "2001-02-23",
    profesiId: 4,
    statusPegawaiId: 5,
    gajiPokok: 150000,
    unitKerjaId: 2,
    createdAt: currentDate,
    updatedAt: currentDate,
  },
];
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("pegawais", pegawais, {
      updateOnDuplicate: [
        "nip",
        "nik",
        "nama",
        "alamat",
        "tanggalLahir",
        "tempatLahir",

        "jabatan",
        "unitKerjaId",
        "statusPegawaiId",
        "profesiId",

        "updatedAt",
        "createdAt",
      ],
    });
  },

  async down(queryInterface, Sequelize) {
    // biasanya tidak perlu rollback untuk data pegawai
  },
};
